// RuoYi-React/src/views/monitor/server/index.tsx
// 服务监控(server) —— features.serverMonitor 降级 + Descriptions 信息卡

import { useEffect, useState } from 'react'
import { Card, Col, Progress, Row, Typography } from 'antd'
import { getServer } from '@/api/monitor/server'
import PlatformGate from '@/components/PlatformGate'

interface ServerInfo {
  [k: string]: unknown
  cpu?: { cpuNum?: number; total?: number; sys?: number; used?: number; wait?: number; free?: number }
  mem?: { total?: number; used?: number; free?: number }
  jvm?: { total?: number; max?: number; free?: number; version?: string; home?: string; name?: string; startTime?: string; runTime?: string; used?: number; inputArgs?: string }
  sys?: { computerName?: string; osName?: string; computerIp?: string; osArch?: string }
  sysFiles?: { dirName?: string; sysTypeName?: string; typeName?: string; total?: string; free?: string; used?: string; usage?: number }[]
}

function UsageBar({ title, used, total, unit }: { title: string; used?: number; total?: number; unit: string }) {
  const percent = total ? Math.round(((used || 0) / total) * 100) : 0
  return (
    <div>
      <Typography.Text strong>{title}</Typography.Text>
      <Progress percent={percent} size="small" status={percent > 80 ? 'exception' : 'normal'} />
      <Typography.Text type="secondary">
        {(used || 0).toFixed(1)}{unit} / {(total || 0).toFixed(1)}{unit}
      </Typography.Text>
    </div>
  )
}

export default function Server() {
  const [info, setInfo] = useState<ServerInfo>({})
  const [loaded, setLoaded] = useState(false)

  useEffect(() => {
    // 基准：serverMonitor !== false 才拉数据
    getServer().then((res) => {
      const data = (res as unknown as { data: ServerInfo }).data
      setInfo(data || {})
      setLoaded(true)
    })
  }, [])

  const cpu = info.cpu || {}
  const mem = info.mem || {}
  const jvm = info.jvm || {}
  const sys = info.sys || {}

  return (
    <PlatformGate feature="serverMonitor" subtitle="服务监控在当前后端运行时未实现，暂不可用。">
      {(enabled) =>
        enabled && loaded ? (
          <div style={{ padding: 16 }}>
            <Row gutter={[16, 16]}>
              <Col xs={24} md={8}><Card title="CPU"><UsageBar title="CPU 使用率" used={cpu.used} total={cpu.total} unit="%" /></Card></Col>
              <Col xs={24} md={8}><Card title="内存"><UsageBar title="内存使用率" used={mem.used} total={mem.total} unit="GB" /></Card></Col>
              <Col xs={24} md={8}><Card title="JVM">
                <UsageBar title="JVM 使用率" used={jvm.used} total={jvm.max} unit="GB" />
                <Typography.Text type="secondary">Java 版本 {jvm.version || '-'} · 启动 {jvm.startTime || '-'}</Typography.Text>
              </Card></Col>
            </Row>
            <Row gutter={[16, 16]} style={{ marginTop: 16 }}>
              <Col xs={24} md={12}><Card title="系统信息">
                <Typography.Text>主机：{sys.computerName || '-'} · IP：{sys.computerIp || '-'}</Typography.Text><br />
                <Typography.Text>系统：{sys.osName || '-'} · 架构：{sys.osArch || '-'}</Typography.Text>
              </Card></Col>
              <Col xs={24} md={12}><Card title="磁盘状态">
                {(info.sysFiles || []).map((f, i) => (
                  <div key={i} style={{ marginBottom: 8 }}>
                    <Typography.Text>{f.dirName}（{f.sysTypeName}）</Typography.Text>
                    <Progress percent={f.usage} size="small" status={(f.usage || 0) > 80 ? 'exception' : 'normal'} />
                    <Typography.Text type="secondary">{f.used} / {f.total}（剩余 {f.free}）</Typography.Text>
                  </div>
                ))}
              </Card></Col>
            </Row>
          </div>
        ) : null
      }
    </PlatformGate>
  )
}

// RuoYi-Vue3/src/views/monitor/server/index.vue
<template>
  <el-result v-if="!features.serverMonitor" icon="info" title="该功能仅 Java 版提供"
    sub-title="服务监控在当前后端运行时未实现，暂不可用。">
    <template #extra>
      <el-button type="primary" @click="getPlatform">重新检测</el-button>
    </template>
  </el-result>
  <div v-else class="app-container">
    <el-row :gutter="10">
      <el-col :span="12" class="card-box">
        <el-card>
          <template #header><Cpu style="width: 1em; height: 1em; vertical-align: middle;" /> <span style="vertical-align: middle;">CPU</span></template>
          <div class="el-table el-table--enable-row-hover el-table--medium">
            <table cellspacing="0" style="width: 100%;">
              <thead>
                <tr>
                  <th class="el-table__cell is-leaf"><div class="cell">属性</div></th>
                  <th class="el-table__cell is-leaf"><div class="cell">值</div></th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td class="el-table__cell is-leaf"><div class="cell">核心数</div></td>
                  <td class="el-table__cell is-leaf"><div class="cell" v-if="server.cpu">{{ server.cpu.cpuNum }}</div></td>
                </tr>
                <tr>
                  <td class="el-table__cell is-leaf"><div class="cell">用户使用率</div></td>
                  <td class="el-table__cell is-leaf"><div class="cell" v-if="server.cpu">{{ server.cpu.used }}%</div></td>
                </tr>
                <tr>
                  <td class="el-table__cell is-leaf"><div class="cell">系统使用率</div></td>
                  <td class="el-table__cell is-leaf"><div class="cell" v-if="server.cpu">{{ server.cpu.sys }}%</div></td>
                </tr>
                <tr>
                  <td class="el-table__cell is-leaf"><div class="cell">当前空闲率</div></td>
                  <td class="el-table__cell is-leaf"><div class="cell" v-if="server.cpu">{{ server.cpu.free }}%</div></td>
                </tr>
              </tbody>
            </table>
          </div>
        </el-card>
      </el-col>

      <el-col :span="12" class="card-box">
        <el-card>
          <template #header><Tickets style="width: 1em; height: 1em; vertical-align: middle;" /> <span style="vertical-align: middle;">内存</span></template>
          <div class="el-table el-table--enable-row-hover el-table--medium">
            <table cellspacing="0" style="width: 100%;">
              <thead>
                <tr>
                  <th class="el-table__cell is-leaf"><div class="cell">属性</div></th>
                  <th class="el-table__cell is-leaf"><div class="cell">内存</div></th>
                  <th class="el-table__cell is-leaf"><div class="cell">JVM</div></th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td class="el-table__cell is-leaf"><div class="cell">总内存</div></td>
                  <td class="el-table__cell is-leaf"><div class="cell" v-if="server.mem">{{ server.mem.total }}G</div></td>
                  <td class="el-table__cell is-leaf"><div class="cell" v-if="server.jvm">{{ server.jvm.total }}M</div></td>
                </tr>
                <tr>
                  <td class="el-table__cell is-leaf"><div class="cell">已用内存</div></td>
                  <td class="el-table__cell is-leaf"><div class="cell" v-if="server.mem">{{ server.mem.used}}G</div></td>
                  <td class="el-table__cell is-leaf"><div class="cell" v-if="server.jvm">{{ server.jvm.used}}M</div></td>
                </tr>
                <tr>
                  <td class="el-table__cell is-leaf"><div class="cell">剩余内存</div></td>
                  <td class="el-table__cell is-leaf"><div class="cell" v-if="server.mem">{{ server.mem.free }}G</div></td>
                  <td class="el-table__cell is-leaf"><div class="cell" v-if="server.jvm">{{ server.jvm.free }}M</div></td>
                </tr>
                <tr>
                  <td class="el-table__cell is-leaf"><div class="cell">使用率</div></td>
                  <td class="el-table__cell is-leaf"><div class="cell" v-if="server.mem" :class="{'text-danger': server.mem.usage > 80}">{{ server.mem.usage }}%</div></td>
                  <td class="el-table__cell is-leaf"><div class="cell" v-if="server.jvm" :class="{'text-danger': server.jvm.usage > 80}">{{ server.jvm.usage }}%</div></td>
                </tr>
              </tbody>
            </table>
          </div>
        </el-card>
      </el-col>

      <el-col :span="24" class="card-box">
        <el-card>
          <template #header><Monitor style="width: 1em; height: 1em; vertical-align: middle;" /> <span style="vertical-align: middle;">服务器信息</span></template>
          <div class="el-table el-table--enable-row-hover el-table--medium">
            <table cellspacing="0" style="width: 100%;">
              <tbody>
                <tr>
                  <td class="el-table__cell is-leaf"><div class="cell">服务器名称</div></td>
                  <td class="el-table__cell is-leaf"><div class="cell" v-if="server.sys">{{ server.sys.computerName }}</div></td>
                  <td class="el-table__cell is-leaf"><div class="cell">操作系统</div></td>
                  <td class="el-table__cell is-leaf"><div class="cell" v-if="server.sys">{{ server.sys.osName }}</div></td>
                </tr>
                <tr>
                  <td class="el-table__cell is-leaf"><div class="cell">服务器IP</div></td>
                  <td class="el-table__cell is-leaf"><div class="cell" v-if="server.sys">{{ server.sys.computerIp }}</div></td>
                  <td class="el-table__cell is-leaf"><div class="cell">系统架构</div></td>
                  <td class="el-table__cell is-leaf"><div class="cell" v-if="server.sys">{{ server.sys.osArch }}</div></td>
                </tr>
              </tbody>
            </table>
          </div>
        </el-card>
      </el-col>

      <el-col :span="24" class="card-box">
        <el-card>
          <template #header><CoffeeCup style="width: 1em; height: 1em; vertical-align: middle;" /> <span style="vertical-align: middle;">Java虚拟机信息</span></template>
          <div class="el-table el-table--enable-row-hover el-table--medium">
            <table cellspacing="0" style="width: 100%;table-layout:fixed;">
              <tbody>
                <tr>
                  <td class="el-table__cell is-leaf"><div class="cell">Java名称</div></td>
                  <td class="el-table__cell is-leaf"><div class="cell" v-if="server.jvm">{{ server.jvm.name }}</div></td>
                  <td class="el-table__cell is-leaf"><div class="cell">Java版本</div></td>
                  <td class="el-table__cell is-leaf"><div class="cell" v-if="server.jvm">{{ server.jvm.version }}</div></td>
                </tr>
                <tr>
                  <td class="el-table__cell is-leaf"><div class="cell">启动时间</div></td>
                  <td class="el-table__cell is-leaf"><div class="cell" v-if="server.jvm">{{ server.jvm.startTime }}</div></td>
                  <td class="el-table__cell is-leaf"><div class="cell">运行时长</div></td>
                  <td class="el-table__cell is-leaf"><div class="cell" v-if="server.jvm">{{ server.jvm.runTime }}</div></td>
                </tr>
                <tr>
                  <td colspan="1" class="el-table__cell is-leaf"><div class="cell">安装路径</div></td>
                  <td colspan="3" class="el-table__cell is-leaf"><div class="cell" v-if="server.jvm">{{ server.jvm.home }}</div></td>
                </tr>
                <tr>
                  <td colspan="1" class="el-table__cell is-leaf"><div class="cell">项目路径</div></td>
                  <td colspan="3" class="el-table__cell is-leaf"><div class="cell" v-if="server.sys">{{ server.sys.userDir }}</div></td>
                </tr>
                <tr>
                  <td colspan="1" class="el-table__cell is-leaf"><div class="cell">运行参数</div></td>
                  <td colspan="3" class="el-table__cell is-leaf"><div class="cell" v-if="server.jvm">{{ server.jvm.inputArgs }}</div></td>
                </tr>
              </tbody>
            </table>
          </div>
        </el-card>
      </el-col>

      <el-col :span="24" class="card-box">
        <el-card>
          <template #header><MessageBox style="width: 1em; height: 1em; vertical-align: middle;" /> <span style="vertical-align: middle;">磁盘状态</span></template>
          <div class="el-table el-table--enable-row-hover el-table--medium">
            <table cellspacing="0" style="width: 100%;">
              <thead>
                <tr>
                  <th class="el-table__cell el-table__cell is-leaf"><div class="cell">盘符路径</div></th>
                  <th class="el-table__cell is-leaf"><div class="cell">文件系统</div></th>
                  <th class="el-table__cell is-leaf"><div class="cell">盘符类型</div></th>
                  <th class="el-table__cell is-leaf"><div class="cell">总大小</div></th>
                  <th class="el-table__cell is-leaf"><div class="cell">可用大小</div></th>
                  <th class="el-table__cell is-leaf"><div class="cell">已用大小</div></th>
                  <th class="el-table__cell is-leaf"><div class="cell">已用百分比</div></th>
                </tr>
              </thead>
              <tbody v-if="server.sysFiles">
                <tr v-for="(sysFile, index) in server.sysFiles" :key="index">
                  <td class="el-table__cell is-leaf"><div class="cell">{{ sysFile.dirName }}</div></td>
                  <td class="el-table__cell is-leaf"><div class="cell">{{ sysFile.sysTypeName }}</div></td>
                  <td class="el-table__cell is-leaf"><div class="cell">{{ sysFile.typeName }}</div></td>
                  <td class="el-table__cell is-leaf"><div class="cell">{{ sysFile.total }}</div></td>
                  <td class="el-table__cell is-leaf"><div class="cell">{{ sysFile.free }}</div></td>
                  <td class="el-table__cell is-leaf"><div class="cell">{{ sysFile.used }}</div></td>
                  <td class="el-table__cell is-leaf"><div class="cell" :class="{'text-danger': sysFile.usage > 80}">{{ sysFile.usage }}%</div></td>
                </tr>
              </tbody>
            </table>
          </div>
        </el-card>
      </el-col>
    </el-row>
  </div>
</template>

<script setup>
import { getServer } from '@/api/monitor/server'
import { getPlatformInfo } from '@/api/platform'

const server = ref([])
const features = ref({ serverMonitor: true })
const { proxy } = getCurrentInstance()

function getList() {
  proxy.$modal.loading("正在加载服务监控数据，请稍候！")
  getServer().then(response => {
    server.value = response.data
    proxy.$modal.closeLoading()
  })
}

function getPlatform() {
  getPlatformInfo().then(response => {
    features.value = response.features || {}
    if (features.value.serverMonitor !== false) getList()
  })
}

getPlatform()
</script>
